local bootVersion = 1.0
local path = "gghjk-system/web-client.lua"
local bootFile = "/disk/internet/Server"

term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
term.clear()
term.setCursorPos(1,1)
print("GGHJK System - Bootloader " .. bootVersion)
print("Kontrola integrity systemu...")
sleep(2)  
term.setTextColor(colors.white)  
term.write("[")
term.setTextColor(colors.orange)
term.write("#####")
term.setTextColor(colors.white)
term.write("] Spouští se...")
sleep(10)
term.clear()
term.setCursorPos(1,1)
term.setTextColor(colors.white)
term.write("[")
term.setTextColor(colors.green)
term.write(" OK ")
term.setTextColor(colors.white)
term.write("] Kontrola integrity dokončena.")
sleep(2)
term.clear()
term.setCursorPos(1,1)
term.setTextColor(colors.white)
term.write("[")
term.setTextColor(colors.green)
term.write(" OK ")
term.setTextColor(colors.white)
term.write("] Spouští se...")
sleep(2)
term.clear()
term.setCursorPos(1,1)
term.setTextColor(colors.white)
term.write("[")
term.setTextColor(colors.green)
term.write(" OK ")
term.setTextColor(colors.white)
term.write("] Kontrola integrity dokončena.")
sleep(2)
shell.run(bootFile)
